image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      go get github.com/spf13/cobra/cobra
      go build
    command: |
      ./mycli --help
vscode:
  extensions:
    - golang.go
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
hostRequirements:
  cpu: 6
  memory: 3288mb
  storage: 30gb